# Generated by Django 6.0.2 on 2026-04-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                default=1,
                help_text="Периодичность в днях",
                verbose_name="Периодичность привычки (в днях)",
            ),
        ),
    ]
