# Generated by Django 6.0.2 on 2026-04-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_period"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_enjoyable_habit",
            field=models.BooleanField(
                default=False, verbose_name="Признак приятной привычки"
            ),
        ),
    ]
