# Generated by Django 6.0.2 on 2026-04-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_is_enjoyable_habit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time",
            field=models.TimeField(
                verbose_name="время, когда необходимо выполнять привычку"
            ),
        ),
    ]
